GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgwOTgzNzIsImV4cCI6MTYwODEwMTk3MiwiYXVkIjoiNWZkOTk3ZjE1NDZhZDkyZWYwZWEzZTVkIiwiaXNzIjoiQ292aWQxOS5jb20ifQ.RXOTn1T7Fk-Xzxujyq4ma4s8staPehSg0DtCSrwYE00

###Login Route

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dan123@gmail.com",
    "password": "Beczka12"
}

###Register Route

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "dan123@gmail.com",
    "password": "Beczka12"
}

###Refresh token Route

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgwODk3NjIsImV4cCI6MTYzOTY0NzM2MiwiYXVkIjoiNWZkOTU4ZTE2OGJmOGYzZjUwM2E1NGJiIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.6bsosiR0eL46iI9QlZBEt6VrwCIXEJGkpuQY289CwUM"
}

###Logout

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgwODgwMTEsImV4cCI6MTYzOTY0NTYxMSwiYXVkIjoiNWZkOTU4ZTE2OGJmOGYzZjUwM2E1NGJiIiwiaXNzIjoiQ292aWQxOS5jb20ifQ.MvzcSJWTCkS8f6zQV-rSaUuZy7klMydiUsktXOnZRwo"
}