GET http://localhost:3000/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg0ODY2NzUsImV4cCI6MTYwODQ5MDI3NSwiYXVkIjoiNWZkZjhmMTMzOWViMGUyMjYwZThkYmI0IiwiaXNzIjoiQ292aWQxOS5jb20ifQ.HET5FGtrElf_b4BTmXaH2_B6n1IUqzrWXLESRbl0CGg

###Login Route

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dan123@gmail.com",
    "password": "Beczka12!"
}

###Register Route

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "dan123@gmail.com",
    "password": "Beczka12!"
}

###Refresh token Routes

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg0ODY4NjUsImV4cCI6MTY0MDA0NDQ2NSwiYXVkIjoiNWZkZjhmMTMzOWViMGUyMjYwZThkYmI0IiwiaXNzIjoiQ292aWQxOS5jb20ifQ.4oyOeUzOEqqP-qzrdnCYuCDDyEhtyoUVrxsUqZv4bXU"
}

###Logout

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDg0ODY4NjUsImV4cCI6MTY0MDA0NDQ2NSwiYXVkIjoiNWZkZjhmMTMzOWViMGUyMjYwZThkYmI0IiwiaXNzIjoiQ292aWQxOS5jb20ifQ.4oyOeUzOEqqP-qzrdnCYuCDDyEhtyoUVrxsUqZv4bXU"
}
