GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDc5MzcyNTksImV4cCI6MTYwNzk0MDg1OSwiYXVkIjoiNWZkNzJjZWIzMWFlMTM0YTBjZjQ0MjVjIiwiaXNzIjoiQ292aWQxOS5jb20ifQ._IxWe8MbAUYZlD0QFbTShSlAJqtjomgrAleBDNZXm3I

###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "nathanallen@gmail.com",
    "password": "Beczka12"
}

###Register Route

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "nathanallen@gmail.com",
    "password": "Beczka12"
}

###Refresh token Route

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDc5MzcyNTksImV4cCI6MTYzOTQ5NDg1OSwiYXVkIjoiNWZkNzJjZWIzMWFlMTM0YTBjZjQ0MjVjIiwiaXNzIjoiQ292aWQxOS5jb20ifQ.-C53_rgs5mX_n1WArfQSbnA0lnuB8NXo2W0R94e_vFY"
}

###Logout

DELETE http://localhost:3000/auth/logout